#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Keras_Applications
Version  : 1.0.5
Release  : 11
URL      : https://files.pythonhosted.org/packages/60/27/a25dfc6e49a6ab3de2d5f23fdb851f18d45ea9867a0955906a5c488ebbe2/Keras_Applications-1.0.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/60/27/a25dfc6e49a6ab3de2d5f23fdb851f18d45ea9867a0955906a5c488ebbe2/Keras_Applications-1.0.5.tar.gz
Summary  : Reference implementations of popular deep learning models
Group    : Development/Tools
License  : MIT
Requires: Keras_Applications-python3
Requires: Keras_Applications-python
Requires: h5py
Requires: numpy
BuildRequires : Keras
BuildRequires : buildreq-distutils3
BuildRequires : h5py
BuildRequires : numpy

%description
Keras Applications is the `applications` module of
        the Keras deep learning library.
        It provides model definitions and pre-trained weights for a number
        of popular archictures, such as VGG16, ResNet50, Xception, MobileNet, and more.

%package python
Summary: python components for the Keras_Applications package.
Group: Default
Requires: Keras_Applications-python3 = %{version}-%{release}
Provides: keras_applications-python

%description python
python components for the Keras_Applications package.


%package python3
Summary: python3 components for the Keras_Applications package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Keras_Applications package.


%prep
%setup -q -n Keras_Applications-1.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538151856
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
